### ISSUE TITLE
validation of medical content 

### ISSUE THREAD

**Issue by ziegm** [hl7ch/ch-ips#5]
@pjolo
Please validate the medical content (use case)

**Comment by pjolo** [comment]
@ziegm: The validation of the use case has been completed. I have added the adjustments in the text

DE:
Frau [Monika Wegmüller](https://fhir.ch/ig/ch-ips/Patient-MonikaWegmueller.html), geboren am 15. Mai 1943, kommt am 26. April 2024 mit plötzlich aufgetretenem Unwohlsein, Schwindel und Atembeschwerden in die Notaufnahme. Dort wird sie von einem Team aus ärztlichem Fachpersonal und Pflegepersonal betreut. Die verantwortliche Ärztin im Spital, Dr. Martina Meier, ruft das aktuellste [IPS Dokument (11. Januar 2024)](https://fhir.ch/ig/ch-ips/Bundle-UC1-SwissIpsDocument1.html) von Frau Wegmüller ab, welches der [Hausarzt](https://fhir.ch/ig/ch-ips/PractitionerRole-FamilienHausarztAtHausarzt.html) am 11. Januar 2024 erstellt hat. Frau Dr. Meier sieht darin dokumentiert, dass Frau Wegmüller an [Diabetes](https://fhir.ch/ig/ch-ips/Condition-DiabetesMellitus.html) und Bluthochdruck leidet und deswegen [Metformin](https://fhir.ch/ig/ch-ips/MedicationStatement-MedStatMetformin.html) und Candesartan einnimmt, ausserdem ist eine koronare Herzkrankheit bekannt, weswegen Frau Wegmüller vor 2 Jahren einen Stent erhalten hat. Frau Wegmüller hat [keine bekannten Allergien](https://fhir.ch/ig/ch-ips/AllergyIntolerance-NoKnownAllergy.html). 
Aufgrund dieser Vorinformationen vermutet Dr. Meier als Grund für das Unwohlsein und die Atembeschwerden einen Herzinfarkt, der sich dann auch im EKG und den Laboruntersuchungen bestätigt. Frau Wegmüller wird ins Herzkatheterlabor gebracht, wo sich zeigt, dass ein Herzkranzgefäss beinahe verschlossen ist und sie einen weiteren Stent braucht. Weil Frau Dr. Meier so gut informiert war konnte sie schnell richtig handeln und so geht es Frau Wegmüller schnell besser. Zur Überwachung wird sie auf die kardiologische Überwachungsstation (Kardio-IMC) aufgenommen. 
Dort wird sie weiterhin von [Dr. Meier](https://fhir.ch/ig/ch-ips/PractitionerRole-869a4dd9-3a4a-4838-ad1e-42453d341147.html) betreut und am Ende des Spitalaufenthalts wird ein neues [IPS Dokument (3. Mai 2024)](https://fhir.ch/ig/ch-ips/Bundle-UC1-SwissIpsDocument2.html) mit den aktuellsten und ergänzten Informationen für Fr. Wegmüller erstellt.

FR: 
Madame [Monika Wegmüller](https://fhir.ch/ig/ch-ips/Patient-MonikaWegmueller.html), née le 15 mai 1943, se rend aux urgences le 26 avril 2024 pour un malaise soudain, des vertiges et des difficultés respiratoires. Elle y est prise en charge par une équipe composée de personnel médical spécialisé et de personnel infirmier. Le médecin responsable à l'hôpital, Dr Martina Meier, récupère le [document IPS](https://github.com/hl7ch/ch-ips/issues/%C2%AB) le plus récent [(11 janvier 2024)](https://github.com/hl7ch/ch-ips/issues/%C2%AB) de Mme Wegmüller, établi par le [médecin de famille](https://github.com/hl7ch/ch-ips/issues/%C2%AB) le 11 janvier 2024. Dr Meier y voit documenté que Mme Wegmüller souffre de [diabète](https://github.com/hl7ch/ch-ips/issues/%C2%AB) et d'hypertension, raison pour laquelle elle prend [de la metformine](https://github.com/hl7ch/ch-ips/issues/%C2%AB) et du candesartan, et qu'une maladie coronarienne est connue, raison pour laquelle Mme Wegmüller a reçu une endoprothèse il y a deux ans. Mme Wegmüller n'a [pas d'allergie connue](https://fhir.ch/ig/ch-ips/AllergyIntolerance-NoKnownAllergy.html). 
Sur la base de ces informations préliminaires, Dr Meier soupçonne un infarctus du myocarde d'être à l'origine du malaise et des difficultés respiratoires, ce que confirment ensuite l'ECG et les examens de laboratoire. Mme Wegmüller est emmenée au laboratoire de cathétérisme cardiaque, où il s'avère qu'une artère coronaire est presque bouchée et qu'elle a besoin d'une autre endoprothèse. Comme Dr Meier était si bien informée, elle a pu agir rapidement et Mme Wegmüller se sent rapidement mieux. Pour la surveillance, elle est admise dans l'unité de soins intensifs en cardiologie (Cardio-IMC).
Là, elle continuera à être suivie par [Dr Meier](https://fhir.ch/ig/ch-ips/PractitionerRole-869a4dd9-3a4a-4838-ad1e-42453d341147.html) et, à la fin de son séjour à l'hôpital, un nouveau [document IPS (3 mai 2024)](https://fhir.ch/ig/ch-ips/Bundle-UC1-SwissIpsDocument2.html) sera établi pour Mme Wegmüller avec les informations les plus récentes et complétées.

EN:
Mrs. [Monika Wegmüller](https://fhir.ch/ig/ch-ips/Patient-MonikaWegmueller.html), born on 15 May 1943, comes to the emergency room on 26 April 2024 with sudden onset of malaise, dizziness and breathing difficulties. She is cared for by a team of medical and nursing staff. The doctor in charge at the hospital, Dr. Martina Meier, retrieves Ms Wegmüller's most recent [IPS document (11 January 2024)](https://fhir.ch/ig/ch-ips/Bundle-UC1-SwissIpsDocument1.html), which the [family doctor](https://fhir.ch/ig/ch-ips/PractitionerRole-FamilienHausarztAtHausarzt.html) prepared on 11 January 2024. Dr. Meier sees documented in it that Ms. Wegmüller suffers from [diabetes](https://fhir.ch/ig/ch-ips/Condition-DiabetesMellitus.html) and high blood pressure and therefore takes [metformin](https://fhir.ch/ig/ch-ips/MedicationStatement-MedStatMetformin.html) and candesartan, and that she also has coronary heart disease, which is why Ms. Wegmüller received a stent two years ago. Mrs. Wegmüller has [no known allergies](https://fhir.ch/ig/ch-ips/AllergyIntolerance-NoKnownAllergy.html). 
Based on this preliminary information, Dr. Meier suspects a heart attack as the reason for her discomfort and breathing difficulties, which is confirmed by the ECG and laboratory tests. Mrs. Wegmüller is taken to the cardiac catheterization laboratory, where it is revealed that a coronary vessel is almost blocked and she needs another stent. Because Dr. Meier was so well informed, she was able to act quickly and Mrs. Wegmüller quickly improved. She is admitted to the cardiac monitoring ward (cardio-IMC) for monitoring.
[Dr. Meier](https://github.com/hl7ch/ch-ips/issues/%E2%80%9Chttps:/fhir.ch/ig/ch-ips/PractitionerRole-869a4dd9-3a4a-4838-ad1e-42453d341147.html%E2%80%9D) continues to look after her there and at the end of her hospital stay, a new [IPS document (May 3, 2024)](https://github.com/hl7ch/ch-ips/issues/%E2%80%9Chttps:/fhir.ch/ig/ch-ips/Bundle-UC1-SwissIpsDocument2.html%E2%80%9D) is created for Ms. Wegmüller with the latest and additional information.

**Comment by ziegm** [comment]
ongoing changes:
- Use Case: [EN](), [DE](), [FR]()
- New instances according the use case:
   - ....
- Updated documents:
   - 1
   - 2 
- Changelog

**Comment by ziegm** [comment]
@pjolo 
the adapted use case requires some new resources/entries in the ips documents. could you please provide me with the following details:
- dosage for candesartan
- dosage for metformin
- is it correct to have the same medication after the hospitalization?
- sct code for both stent operations (there are a lot...)
- sct code for heart attack

**Comment by pjolo** [comment]
> @pjolo the adapted use case requires some new resources/entries in the ips documents. could you please provide me with the following details:
> 
> * dosage for candesartan
> * dosage for metformin
> * is it correct to have the same medication after the hospitalization?
> * sct code for both stent operations (there are a lot...)
> * sct code for heart attack

@ziegm 
* Dosage for candesartan 8mg 1-0-0-0
* Dosage for metformin 500mg 1-0-1-0
* After hospitalization, patients receive atorvastatin 40mg 0-0-1-0 and clopidogrel 75mg 1-0-0-0 and aspirin 100mg 1-0-0-0
* sct code for stent operations: This code can be used for both operations: 36969009 |Placement of stent in coronary artery (procedure)
* sct code for heart attack: 22298006 |Myocardial infarction (disorder)|

**Comment by pjolo** [comment]
@ziegm Yes, of course, no problem.

**Comment by ziegm** [comment]
@pjolo which one and how?

and can we adapt the use case as follows:
- in the first document the allergies are not asked (empty section)
- in the second document the allergies are asked and no allergies are known (AllergyIntolerance resource with the code)
so we could represent all different structures of the doc.
https://hl7.org/fhir/uv/ips/2024Sep/Design-Conventions.html#empty-sections--missing-data

**Comment by pjolo** [comment]
@ziegm 
atorvastatin 40mg can be given as a split dose: 0.5 - 0 - 0.5 - 0
Yes, the use case can be adapted as you propose.

**Comment by ziegm** [comment]
> [@ziegm](https://github.com/ziegm) atorvastatin 40mg can be given as a split dose: 0.5 - 0 - 0.5 - 0 Yes, the use case can be adapted as you propose.

split dosage would be 0.5 - 0 - 1 - 0 (can we use that for atorvastatin?)

**Comment by ziegm** [comment]
@pjolo please review the changes:

- Use Case: [EN](https://build.fhir.org/ig/hl7ch/ch-ips/branches/issue5_validationContent/usecase-english.html), [DE](https://build.fhir.org/ig/hl7ch/ch-ips/branches/issue5_validationContent/usecase-german.html), [FR](https://build.fhir.org/ig/hl7ch/ch-ips/branches/issue5_validationContent/usecase-french.html)
- Updated documents:
   - [Document 1 (11.01.2024)](https://build.fhir.org/ig/hl7ch/ch-ips/branches/issue5_validationContent/Bundle-UC1-SwissIpsDocument1.html)
   - [Document 2 (03.05.2024)](https://build.fhir.org/ig/hl7ch/ch-ips/branches/issue5_validationContent/Bundle-UC1-SwissIpsDocument2.html) 
- [Changelog](https://build.fhir.org/ig/hl7ch/ch-ips/branches/issue5_validationContent/changelog.html)

**Comment by pjolo** [comment]
The changes are good
